# Site settings
title: Brendan Rius' blog
email: brendan.rius@gmail.com
description: >
  Hacker with a strong entrepreneurial mind.
  2x founder & ex-freelance.
  College dropout.
  Working with an awesome team to make personalized medicine a reality @Omixy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  brendan-rius

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
